### PR TITLE
Made reusable NativeLanguageDropdown component 

### PR DESCRIPTION
**Pull request by nondescryptid**
# Reusable NativeLanguageDropdown

## Description

This change creates a reusable NativeLanguageDropdown that can be imported and used on components such as NewTeacher/Student, EditTeacher/Student. Cuts down on having to copy-paste methods like filteredLanguageArray etc 

## Test Steps

1. Create a new Student (check that NativeLanguage dropdown filters typing as expected)
2. Create a new Teacher with Native Language and Second Language(check that NativeLanguage dropdown filters typing as expected)
3. Edit student - change NativeLanguage and see if change is reflected on profile
4. Edit teacher - change NativeLanguage and SecondLanguage, check if changes are reflected on teacher profile

### CODE REVIEW

**Comment by thchia** [comment]
@szktm when you can, resolve the conflicts so we can review without worrying if the resolution will change things and invalidate the review (though I think it's a really minor conflict, perhaps someone updated the placeholder on the autocomplete whilst you were component-ising it).

**Comment by nondescryptid** [comment]
@thchia sure! conflicts have been resolved

**Review by therealyingtong — APPROVED** [review]

**Review by dzldebby — APPROVED** [review]
Tested all 4 steps and works as expected :)

**Review by thchia — APPROVED** [review]
Working fine, although I found some other unrelated error. Will document it separately.

**Pull request merged**
