### PR TITLE
IRRC-119: Adds login functionality and frontend protected routes

### PR DESCRIPTION
**Pull request by thchia**
# Frontend Login (currently disabled)

[IRRC-119](https://bootcamp-irrc.atlassian.net/browse/IRRC-119)

This change adds a login functionality to the frontend. Features include:
- Login page
- Redirect to login page if user attempts to access other pages when not logged in
- If redirected to login page, upon logging in, the user will be returned to the page they were trying to access
- Login page can display reasons for being logged out (e.g. if the access token expires)
- There is some excess code related to making this entire feature disabled for now

This is mostly new components and functionality, but one major change I made to existing code was to move the contents of `App.vue` into a `Secure` component. This lets us have a different layout for the Login page (it has no Sidebar).

### Setup

1. Ensure your local database has at least 1 `User`. If you do not, you may create one using the `/users/signup` endpoint.
2. In `frontend/vite.config.js`, change the `IRRC_LOGIN_ENABLED` variable to `true` (**before running the frontend project**).
3. Run the frontend and backend as usual.

### Main Path

1. Do the setup steps.
2. Try to access any page except `/login`. You should be redirected to the login page.
3. Login with correct credentials, you should land back on the page you tried to access in Step 2.

### Wrong Credentials

1. Do the setup steps (if not already).
2. Login with the wrong credentials, you should see an error.

### Logout Reason

1. Do the setup steps (if not already).
2. Visit `/login?reason=expired`, you should see a notification saying your session expired (we will use this later, if you make an API call with an expired token, then we will redirect people to this path so it's clear what happened). It's implemented in a generic way in case there are other reasons in the future.

### CODE REVIEW

**Review by therealyingtong — APPROVED** [review]
Reviewed with @dzldebby

**Review by dzldebby — APPROVED** [review]
Tested all functionalities of set-up, main path, wrong creds, and logout. All of them work as expected. However, while this PR does not touch on the display on `Matching.vue` or `Matched.vue`, there seems to be some additional padding to the Matching table on `Matching.vue` and Matched table on `Matched.vue`. The Screening table is not affected. 

image

image

**Comment by thchia** [comment]
Thanks @dzldebby , gonna mark this as a bug and look at it before merging.

**Comment by thchia** [comment]
@dzldebby the issue you found should be resolved.

**Pull request merged**
