### PR TITLE
refactoring students.vue to use Status.vue component 

### PR DESCRIPTION
**Pull request by nondescryptid**

### CODE REVIEW

**Comment by therealyingtong** [comment]
TODO: same refactor for Teachers.vue

**Review by xuanjane — APPROVED** [review]
LGTM

**Review by therealyingtong — APPROVED** [review]
Tested approval

**Comment by therealyingtong** [comment]
Let's do a similar refactor in `Teachers.vue` (opened https://github.com/TechLadies/irrc-madwish/issues/117 for this)

**Pull request merged**
