### PR TITLE
Add teacher's phone number & double-click on row to link to Teacher's profile page

### PR DESCRIPTION
**Pull request by dzldebby**
# Add teacher's phone number & double-click on row to link to Teacher's profile page

[IRRC-121](https://bootcamp-irrc.atlassian.net/browse/IRRC-121)
[IRRC-122](https://bootcamp-irrc.atlassian.net/browse/IRRC-122)

## Changes made
1. Added teacher's phone number 
2. Added method so that a double-click on each row will link you to Teacher's profile page

## Test Steps

1. Go to Matched table 
2. You should see the teacher's phone number on the table 
3. Double-click on each row. It should take you to the profile page of the Teacher of that specific row

### CODE REVIEW

**Review by thchia — APPROVED** [review]
Untested but looks straightforward.

**Review by aelbore — APPROVED** [review]
looks good to me

**Comment by nondescryptid** [comment]
@dzldebby 

I can double-click to link to the individual profile and see the teacher’s HP number only for /teachers, but cannot do so for /matched (which is what the test steps says to test with). 

/matched does not show teacher's
 HP number and also does not allow double-clicking to go to the teacher's profile 
Screenshot 2021-04-17 at 11 24 41 AM

**Review by nondescryptid — APPROVED** [review]
Clarified with debby that these changes (phone number + double-click to go to profile) are meant for /teachers, and that changes for /matched are being worked on separately. tested and LGTM :)

**Pull request merged**
