### PR TITLE
modified backend to be able to receive NativeLanguageString 

### PR DESCRIPTION
**Pull request by lauratsui**
Modified helpers and routes to pick out the right NativeLanguageID for a NativeLanguageString inserted, or to add new native language if it doesn't exist.

### CODE REVIEW

**Review by nondescryptid — CHANGES_REQUESTED** [review]
POST works great — being able to use NativeLanguageString simplifies things so much! I can't PATCH with NativeLanguageString though. Can this functionality be extended to PATCHing students?

**Comment by thchia** [comment]
@szktm my take - yes we can but let's do it as a separate task/PR.

**Comment by nondescryptid** [comment]
@thchia okie! 
@lauratsui Should new languages added through NativeLanguageString be in uppercase? Guess this is more of a consistency issue since there aren't any practical issues with it right now, given that the backend doesn't create a new language even when I send in "NativeLanguageString":"EnGLIsH" after sending "English". 

Screenshot 2020-11-29 at 3 42 46 PM

**Comment by thchia** [comment]
@szktm good catch. Yes we should uppercase it when inserting.

**Comment by thchia** [comment]
@lauratsui in the latest commit there seem to be a bunch of other files changed, apart from the one that actually needs to be changed.

**Comment by nondescryptid** [comment]
Tried it out and languages are in uppercase after being inserted with NativeLanguageString! Awesome. 

i'll approve this after issues with file changes are resolved — the file changes seem to be reverting the code to an earlier version e.g. student.js removes FullName and reinstates FirstName and LastName.

**Comment by lauratsui** [comment]
Thanks @szktm!! I've reset to the right versions and resolved any merge conflicts.

**Review by nondescryptid — APPROVED** [review]
tried it out again to make sure it works, lgtm! 👍

**Pull request merged**
