### PR TITLE
[IRRC-80] Implement Reasons (for dropping out) & Cleanup Vuex main store

### PR DESCRIPTION
**Pull request by xuanjane**
1. IRRC-80 [https://bootcamp-irrc.atlassian.net/browse/IRRC-80]
2. Move student-related vuex actions to `frontend\src\store\students.js`
3. TODOs(Nice-to-haves): 
- Force Reload page onConfirm status change
- Success message when new dropped-out reason has been successfully added

### CODE REVIEW

**Comment by thchia** [comment]
I know this is still a draft, but commenting so I don't forget.

Perhaps we should add a `ReasonDescription` to the table as well? This way we can display something more readable to the user than `DROPPED_Not available`, unless you planned to parse the reason into something else.

**Comment by therealyingtong** [comment]
> Perhaps we should add a ReasonDescription to the table as well? This way we can display something more readable to the user than DROPPED_Not available, unless you planned to parse the reason into something else.

@thchia we're planning to use `DROPPED` and `UNMATCHED` as prefixes to the reason description, to be parsed out by the frontend. so a new reason for dropping out would be added to the table as (for example) `DROPPED_Student found the program too challenging`.

**Comment by thchia** [comment]
It would have been better to do the Vuex cleanup in a separate PR. The Reasons changes are large and complex, and the Vuex cleanup is low complexity. So we could have reviewed and merged the Vuex store changes quickly if they were in a separate PR. Next time 😆

**Comment by xuanjane** [comment]
> It would have been better to do the Vuex cleanup in a separate PR. The Reasons changes are large and complex, and the Vuex cleanup is low complexity. So we could have reviewed and merged the Vuex store changes quickly if they were in a separate PR. Next time 😆

Noted!

**Review by aelbore — APPROVED** [review]
Looks good to me

**Review by nondescryptid — APPROVED** [review]
Tried it out, LGTM! Was able to add new reasons for dropping out (which then appeared in the dropdown afterwards) and reactivate students for screening after dropping out.

**Comment by xuanjane** [comment]
Thanks @aelbore and @szktm for going through this PR 🙏

**Pull request merged**
