### PR TITLE
Wrap page layout on NewStudent component

### PR DESCRIPTION
**Pull request by dzldebby**

### CODE REVIEW

**Comment by dzldebby** [comment]
@thchia Is it okay to merge it or should I request for reviews?

**Review by thchia — APPROVED** [review]
As discussed the diff is very big but the only significant change you made was to wrap everything in Page right (and some minor CSS tweaks I see)?

**Comment by dzldebby** [comment]
> As discussed the diff is very big but the only significant change you made was to wrap everything in Page right (and some minor CSS tweaks I see)?

Yes, only (1) wrap everything in Page (2) import Page component, (3) adjust margin for the notifications a little with the Page

**Comment by thchia** [comment]
I'm ok if you merge it. But in general let's try to stick to our policy of coach + participant reviews.

**Comment by thchia** [comment]
@dzldebby let's merge this.

**Pull request merged**
