### PR TITLE
Status Update Transaction

### PR DESCRIPTION
**Pull request by xuanjane**
Addresses #77 

Changes to student status should not be made through the students endpoint. Rather they should be made through the status updates endpoint, making sure to provide the `UpdatedBy` field
Any insertion to the status updates table should be made with a corresponding update to the student status in the students table (i.e. the 2 operations are a single transaction)

### CODE REVIEW

**Review by aelbore — APPROVED** [review]
looks good

**Comment by nondescryptid** [comment]
When a request with [{StudentID, EnglishProficiency}] is sent to the screening endpoint, the English Proficiency gets updated but there is no change in StatusID, and the statusUpdates array is empty which suggests that the transaction does not occur. i haven't figured out why it's happening though 

Attached screenshot is of the student after [{"StudentID": 4, "EnglishProficiency": "Little"}] was posted to api/screening
Screenshot 2021-01-23 at 1 03 43 PM

**Comment by therealyingtong** [comment]
Thanks for catching this @szktm. It's because the request is missing an `"UpdatedBy"` field. We'll catch and handle this error.

**Comment by xuanjane** [comment]
> [{"StudentID": 4, "EnglishProficiency": "Little"}]

Hi Tomoe, we have just amended with a check to catch this. Thanks for pointing out! :)

**Review by nondescryptid — APPROVED** [review]
Tried it out (added "UpdatedBy": "IRRCAdmin") and it works now!

**Pull request merged**
