### PR TITLE
[IRRC-91 & 37] Integrate Teacher Profile (update Status)

### PR DESCRIPTION
**Pull request by nondescryptid**
What this PR does 
- changes teacher's status in the backend when the Profile Card buttons are clicked (E.g. unmatch, drop out etc) 
- deletes matches in the matching table that involve a given teacher (who is now unmatched/dropped out) 
- change status of students attached to the teacher 

How to test this PR - flow when teachers drop out/unmatch through the profile
- create a few students and teachers 
- match students to a teacher through Matching table 
- check api/matches to see if matching has succeeded 
- Go to teacher's profile - status of teacher should be Matched
- Click drop out / unmatch
- Check matching table to see if matches have been deleted
- Check if teacher + students' statuses are now Unmatched

TODO in IRRC-37 : 
- where students are the ones dropping/being unmatched, to check if the student is a teacher's only student, and then change the teacher's status if that is true.

### CODE REVIEW

**Comment by therealyingtong** [comment]
Please refer to #95 (ready for review). I recommend refactoring this PR to make use of the matching table.

Note also that one teacher can be matched to multiple students, which means that for teachers:
- `Matched` -> `Matched` status is possible
- `Matched` -> `Unmatched` should unmatch all students

**Comment by nondescryptid** [comment]
@therealyingtong arjay and i were discussing this and we're thinking of merging this first, then opening another PR to create a Matched table so that we can view existing matches in the UI (edit: I realise Jane is working on this, so i will try doing 37 then the Matched table will come in handy for testing), and then finally making another PR for IRRC-37 because IRRC-37 itself seems quite big. 

Then, we can use the Matched table in the UI to test if we can 
1) delete matches that are linked to a given teacherID

- Instead of deleting the match from the database, maybe we can add isDeleted to the schema for matches so that we can "delete" a match by patching isDeleted: True/1 or isDeleted: False/0 so that we have the option of reinstating matches too (as opposed to having them disappear). Only matches with isDeleted: False/0 will appear in the UI 

2) also update statuses for students that are in the matches (from matched → unmatched)

**Comment by therealyingtong** [comment]
@szktm for testing, you can use `localhost:3001/api/matches`.

**Comment by aelbore** [comment]
@therealyingtong I think by this PR we can already test Integration of Teacher Profile from the backend, we can already verify the Teacher is updating the status. 

The things we need to do for the matches
* api for deletion the matches
* integration to student profile
* integration to teacher profile
* integration to matches

matches still in progress we cannot yet verify the whole flow.

**Comment by xuanjane** [comment]
@aelbore @szktm  we've opened a draft PR #107  for displaying the matches table.
If you are planning to work on the deletion API, we can wait for that... or otherwise we can also implement it as part of our PR :)
Feel free to start on the deletion API first, as we are still figuring out a lot of frontend stuffs.

**Comment by nondescryptid** [comment]
@xuanjane @therealyingtong we've got the deletion API up on this PR! we realise we also need to include logic for changing student/teachers' statuses: 
1. If a student is a teacher's only student, then the student unmatching must also lead to a change in the teacher's status. Else, the teacher's status isn't changed
2. When teachers unmatch/drop out, the statuses of all their students must be changed to unmatched. 
Do you need the deletion api for the matches table? if yes we can merge this first, then do the logic for status changes as a separate PR. if not we'll continue working on this PR

**Comment by therealyingtong** [comment]
This PR partly addresses #87.

**Comment by therealyingtong** [comment]
Further unmatching logic to be addressed in [IRRC-25](https://bootcamp-irrc.atlassian.net/browse/IRRC-25)

**Review by therealyingtong — APPROVED** [review]
Tested approval

**Review by xuanjane — APPROVED** [review]
LGTM

**Pull request merged**
