### PR TITLE
[IRRC 52] Integrate backend into Student Profile UI

### PR DESCRIPTION
**Pull request by lauratsui**

### CODE REVIEW

**Review by aelbore — APPROVED** [review]
looks good to me 👍

**Review by nondescryptid — CHANGES_REQUESTED** [review]
Looks good! Quick request - could you add   `<base href="/">` to line 3 in index.html under `<head>`? otherwise http://localhost:3000/students/1 returns error 404 not found

**Review by aelbore — APPROVED** [review]
looks good 👍

**Review by nondescryptid — APPROVED** [review]
I've put the base href thing in a separate tiny PR (https://github.com/TechLadies/irrc-madwish/pull/41) instead as Thomas recommended on this thread https://teamtechladies.slack.com/archives/G018LH37LRE/p1606039172009500.

**Comment by thchia** [comment]
@lauratsui I have resolved the outstanding merge conflict. This is good to merge.

**Pull request merged**
